### ISSUE TITLE
Add example without using loop and if statements 

### ISSUE THREAD

**Issue by paaspaas00** [Naguissa/uTimerBrokerLib#1]
Nice library!! Just tried it on my Arduino Uno and it works a treat!
Just as a minor addition, you could add an example where you just call printf from the callback. I know it's generally bad practice and ISR should be as short as possible, but I don't think in this case it would matter much and you could also tell people why it is bad practice etc for those newcomers that aren't aware of it.
Just another aside, should the variables set in the callbacks in the example be declared as volatile? I dunno really, maybe yes(?)

Congratulations for the lib, really love it, will integrate it in my little project. In version 2 you may think of including my code from my lib "ardutimer", I can help you out with that if you want 😄

**Comment by Naguissa** [comment]
I've seen as your library works and it's a completely different approach.

Yours is way better for few timers or long-period timers.

But I think it would overload MCUs (specially 8MHz AVRs) with few short-period timers. Specially because you're calculating and reattaching timers continuously, and uTimerLib also does few math internally in order to calculate overflows and remaining.

Why don't you publish your broker as Arduino library?

I can help you to finish it, structure it as Arduino library and add it to Arduino's Library Manager.

**Comment by Naguissa** [comment]
Added new example, on version 1.0.2

**Comment by Naguissa** [comment]
Oh, one question I skipped: Yes, variables used in ISRs should be declared volatile. 

It's to indicate compiler to manage that variable specially, and it's used for ISR and threads, where variables can be read and written in different places (inside and outside the ISR or thread).

https://www.arduino.cc/reference/es/language/variables/variable-scope-qualifiers/volatile/
